# Generated by Django 4.0.1 on 2022-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_freelancer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobadvert',
            old_name='price',
            new_name='name',
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='pricemax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='pricemin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='procemid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
