# Generated by Django 4.0.1 on 2022-07-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_pricemax_jobadvert_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='procemid',
            new_name='pricemid',
        ),
    ]
