# Generated by Django 4.0.1 on 2022-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_freelancer_pricemax_alter_freelancer_pricemid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvert',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobadvert',
            name='surname',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
