# Generated by Django 4.0.1 on 2022-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='pricemax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='pricemid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='pricemin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
