# Generated by Django 4.0.1 on 2022-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_freelancer_fname_remove_freelancer_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='priceextra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
