# Generated by Django 4.0.1 on 2022-07-06 10:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_freelancer_priceextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
