# Generated by Django 4.0.1 on 2022-07-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job',
            new_name='freelancer',
        ),
    ]
