# Generated by Django 4.0.1 on 2022-07-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_job_application_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
