# Generated by Django 4.0.1 on 2022-07-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_freelancer_email_freelancer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
