# Generated by Django 4.0.1 on 2022-07-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_freelancer_fname_freelancer_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='lname',
            new_name='lastname',
        ),
    ]
