# Generated by Django 4.0.1 on 2022-07-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_freelancer_deliverydaysforpriceextra_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
